import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import { Header } from "@/componants/website/Header";
import Footer from "@/componants/website/Footer";
import { ToastContainer } from "react-toastify";
import Sub from "@/componants/website/Sub"; // Desktop navigation
import MobileHeader from "@/componants/website/MobileHeader"; // Mobile navigation

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="overflow-hidden">
          <ToastContainer autoClose={500} />

          {/* Desktop Navigation */}
          <div className="lg:block hidden">
            <Header />
            <Sub />
          </div>

          {/* Mobile Navigation */}
          <div className="lg:hidden">
            <MobileHeader />
          </div>

          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
